// Code generated by mockery v2.12.1. DO NOT EDIT.

package sli

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// mockSliGenerator is an autogenerated mock type for the sliGenerator type
type mockSliGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: inputFile
func (_m *mockSliGenerator) Generate(inputFile string) (string, error) {
	ret := _m.Called(inputFile)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(inputFile)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(inputFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSliGenerator creates a new instance of mockSliGenerator. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newMockSliGenerator(t testing.TB) *mockSliGenerator {
	mock := &mockSliGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
